// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Entity } from '../model/entity';
import { FileHints } from '../model/file-hints';
import { KeyOptions } from '../model/key-options';


export class EncryptRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):EncryptRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEncryptRequest(bb:flatbuffers.ByteBuffer, obj?:EncryptRequest):EncryptRequest {
  return (obj || new EncryptRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEncryptRequest(bb:flatbuffers.ByteBuffer, obj?:EncryptRequest):EncryptRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EncryptRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

publicKey():string|null
publicKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
publicKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

options(obj?:KeyOptions):KeyOptions|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new KeyOptions()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

signed(obj?:Entity):Entity|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Entity()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fileHints(obj?:FileHints):FileHints|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new FileHints()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startEncryptRequest(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, publicKeyOffset, 0);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, optionsOffset, 0);
}

static addSigned(builder:flatbuffers.Builder, signedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, signedOffset, 0);
}

static addFileHints(builder:flatbuffers.Builder, fileHintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, fileHintsOffset, 0);
}

static endEncryptRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
