// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetPrivateKeyMetadataRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPrivateKeyMetadataRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPrivateKeyMetadataRequest(bb:flatbuffers.ByteBuffer, obj?:GetPrivateKeyMetadataRequest):GetPrivateKeyMetadataRequest {
  return (obj || new GetPrivateKeyMetadataRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPrivateKeyMetadataRequest(bb:flatbuffers.ByteBuffer, obj?:GetPrivateKeyMetadataRequest):GetPrivateKeyMetadataRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPrivateKeyMetadataRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGetPrivateKeyMetadataRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, privateKeyOffset, 0);
}

static endGetPrivateKeyMetadataRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPrivateKeyMetadataRequest(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetPrivateKeyMetadataRequest.startGetPrivateKeyMetadataRequest(builder);
  GetPrivateKeyMetadataRequest.addPrivateKey(builder, privateKeyOffset);
  return GetPrivateKeyMetadataRequest.endGetPrivateKeyMetadataRequest(builder);
}
}
