// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class VerifyFileRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):VerifyFileRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVerifyFileRequest(bb:flatbuffers.ByteBuffer, obj?:VerifyFileRequest):VerifyFileRequest {
  return (obj || new VerifyFileRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVerifyFileRequest(bb:flatbuffers.ByteBuffer, obj?:VerifyFileRequest):VerifyFileRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VerifyFileRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

signature():string|null
signature(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
signature(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

input():string|null
input(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
input(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

publicKey():string|null
publicKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
publicKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startVerifyFileRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSignature(builder:flatbuffers.Builder, signatureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, signatureOffset, 0);
}

static addInput(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, inputOffset, 0);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, publicKeyOffset, 0);
}

static endVerifyFileRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVerifyFileRequest(builder:flatbuffers.Builder, signatureOffset:flatbuffers.Offset, inputOffset:flatbuffers.Offset, publicKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  VerifyFileRequest.startVerifyFileRequest(builder);
  VerifyFileRequest.addSignature(builder, signatureOffset);
  VerifyFileRequest.addInput(builder, inputOffset);
  VerifyFileRequest.addPublicKey(builder, publicKeyOffset);
  return VerifyFileRequest.endVerifyFileRequest(builder);
}
}
