// Objective-C API for talking to github.com/jerson/openpgp-mobile/mobile Go package.
//   gobind -lang=objc github.com/jerson/openpgp-mobile/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Openpgp_H__
#define __Openpgp_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class OpenpgpOpenPGP;

@interface OpenpgpOpenPGP : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSString* _Nonnull)decrypt:(NSString* _Nullable)message privateKey:(NSString* _Nullable)privateKey passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encrypt:(NSString* _Nullable)message publicKey:(NSString* _Nullable)publicKey error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)sign:(NSString* _Nullable)message publicKey:(NSString* _Nullable)publicKey privateKey:(NSString* _Nullable)privateKey passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
- (BOOL)verify:(NSString* _Nullable)signature message:(NSString* _Nullable)message publicKey:(NSString* _Nullable)publicKey ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT OpenpgpOpenPGP* _Nullable OpenpgpNewOpenPGP(void);

#endif
