// automatically generated by the FlatBuffers compiler, do not modify

package com.reactnativefastopenpgp.model

@Suppress("unused")
@ExperimentalUnsignedTypes
class Compression private constructor() {
    companion object {
        const val NONE: Int = 0
        const val ZLIB: Int = 1
        const val ZIP: Int = 2
        val names : Array<String> = arrayOf("NONE", "ZLIB", "ZIP")
        fun name(e: Int) : String = names[e]
    }
}
