// automatically generated by the FlatBuffers compiler, do not modify

package com.reactnativefastopenpgp.model

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class DecryptRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DecryptRequest {
        __init(_i, _bb)
        return this
    }
    val message : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val messageAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun messageInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val privateKey : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val privateKeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun privateKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val passphrase : String?
        get() {
            val o = __offset(8)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val passphraseAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun passphraseInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val options : KeyOptions? get() = options(KeyOptions())
    fun options(obj: KeyOptions) : KeyOptions? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_1_12_0()
        fun getRootAsDecryptRequest(_bb: ByteBuffer): DecryptRequest = getRootAsDecryptRequest(_bb, DecryptRequest())
        fun getRootAsDecryptRequest(_bb: ByteBuffer, obj: DecryptRequest): DecryptRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDecryptRequest(builder: FlatBufferBuilder, messageOffset: Int, privateKeyOffset: Int, passphraseOffset: Int, optionsOffset: Int) : Int {
            builder.startTable(4)
            addOptions(builder, optionsOffset)
            addPassphrase(builder, passphraseOffset)
            addPrivateKey(builder, privateKeyOffset)
            addMessage(builder, messageOffset)
            return endDecryptRequest(builder)
        }
        fun startDecryptRequest(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addMessage(builder: FlatBufferBuilder, message: Int) = builder.addOffset(0, message, 0)
        fun addPrivateKey(builder: FlatBufferBuilder, privateKey: Int) = builder.addOffset(1, privateKey, 0)
        fun addPassphrase(builder: FlatBufferBuilder, passphrase: Int) = builder.addOffset(2, passphrase, 0)
        fun addOptions(builder: FlatBufferBuilder, options: Int) = builder.addOffset(3, options, 0)
        fun endDecryptRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
