// automatically generated by the FlatBuffers compiler, do not modify

package com.reactnativefastopenpgp.model

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

/**
 * An Entity represents the components of an OpenPGP key: a primary public key
 * (which must be a signing key), one or more identities claimed by that key,
 * and zero or more subkeys, which may be encryption keys.
 */
@Suppress("unused")
@ExperimentalUnsignedTypes
class Entity : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Entity {
        __init(_i, _bb)
        return this
    }
    val publicKey : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val publicKeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun publicKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val privateKey : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val privateKeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun privateKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val passphrase : String?
        get() {
            val o = __offset(8)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val passphraseAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun passphraseInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_2_0_0()
        fun getRootAsEntity(_bb: ByteBuffer): Entity = getRootAsEntity(_bb, Entity())
        fun getRootAsEntity(_bb: ByteBuffer, obj: Entity): Entity {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEntity(builder: FlatBufferBuilder, publicKeyOffset: Int, privateKeyOffset: Int, passphraseOffset: Int) : Int {
            builder.startTable(3)
            addPassphrase(builder, passphraseOffset)
            addPrivateKey(builder, privateKeyOffset)
            addPublicKey(builder, publicKeyOffset)
            return endEntity(builder)
        }
        fun startEntity(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addPublicKey(builder: FlatBufferBuilder, publicKey: Int) = builder.addOffset(0, publicKey, 0)
        fun addPrivateKey(builder: FlatBufferBuilder, privateKey: Int) = builder.addOffset(1, privateKey, 0)
        fun addPassphrase(builder: FlatBufferBuilder, passphrase: Int) = builder.addOffset(2, passphrase, 0)
        fun endEntity(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
