// automatically generated by the FlatBuffers compiler, do not modify

package com.reactnativefastopenpgp.model

@Suppress("unused")
@ExperimentalUnsignedTypes
class Hash private constructor() {
    companion object {
        const val SHA256: Int = 0
        const val SHA224: Int = 1
        const val SHA384: Int = 2
        const val SHA512: Int = 3
        val names : Array<String> = arrayOf("SHA256", "SHA224", "SHA384", "SHA512")
        fun name(e: Int) : String = names[e]
    }
}
