// automatically generated by the FlatBuffers compiler, do not modify

package com.reactnativefastopenpgp.model

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class StringResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StringResponse {
        __init(_i, _bb)
        return this
    }
    val output : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val outputAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun outputInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val error : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val errorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun errorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_1_12_0()
        fun getRootAsStringResponse(_bb: ByteBuffer): StringResponse = getRootAsStringResponse(_bb, StringResponse())
        fun getRootAsStringResponse(_bb: ByteBuffer, obj: StringResponse): StringResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStringResponse(builder: FlatBufferBuilder, outputOffset: Int, errorOffset: Int) : Int {
            builder.startTable(2)
            addError(builder, errorOffset)
            addOutput(builder, outputOffset)
            return endStringResponse(builder)
        }
        fun startStringResponse(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addOutput(builder: FlatBufferBuilder, output: Int) = builder.addOffset(0, output, 0)
        fun addError(builder: FlatBufferBuilder, error: Int) = builder.addOffset(1, error, 0)
        fun endStringResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
